### ISSUE TITLE
Possible problem with HTML syntax error

### ISSUE THREAD

**Issue by felquis** [remcohaszing/grunt-angular-templatecache#4]
Hi, 

This plugin was breaking my terminal when I put a syntax error in a file, the error was this one:
```html
<button ng-if="following"  && platform === 'ios'"></button>
```

Would be great - if possible - if the task just break and point me where is the problem.

Congrats for the great plugin.

**Comment by remcohaszing** [comment]
The HTML is not parsed by this Grunt task, so it can't really go into detail about the error. If you want to validate your HTML files I recommend using [grunt-htmllint](https://www.npmjs.com/package/grunt-htmllint).
